/**
 * The buildings of one chunk, as geometry (spec sections 9.2, 10.1, 10.3).
 *
 * `buildings.ts` says where a building stands and what kind it is. This says
 * what it looks like: the shell that is generated for it and where that shell
 * is placed. `building-plan.ts` says how big it is and what ground it may
 * cover; `building-hull.ts` outlines it. This file is the door onto all three.
 *
 * A tower and a mid-rise block are generated by `SkyscraperGenerator`, which
 * gives the chamfers, setbacks, string courses and varied bays of spec section
 * 10.3 from one seed. Every other kind is a few boxes from `block-mesh.ts`; so
 * is a tower on a lot too narrow to generate a facade on, because the generator
 * needs room for its bays.
 *
 * A building never stands on a road, by construction (spec section 1.1). The lot
 * is already inside its parcel, and a parcel is the land the road footprint
 * leaves; the shell is then fitted inside the room the plan leaves it. Whatever
 * still reaches past that room is taken in by the scale of the placement, so
 * the last step is measured rather than estimated, and the sweep checks it.
 *
 * A building's own frame has the middle of its lot at the origin, `x` along the
 * frontage, `z` towards the road and `y` up from the ground it stands on. The
 * matrix of a placement is what puts that frame in the world. A shell is built
 * square in that frame; where its lot shares a side edge, its places are then
 * leaned along `x` to follow the lot's side edges, which a matrix cannot do on
 * a lot that is wider at its front than at its back.
 *
 * Nothing here touches the renderer or TSL, so it runs headless and the tests
 * read it directly.
 */
import { Box3, BufferAttribute, BufferGeometry, Color, Matrix4, Quaternion, Vector3 } from 'three';
import { SkyscraperGenerator, pickBuildingColor } from 'three/examples/jsm/generators/city/SkyscraperGenerator.js';
import { hashInts } from '../core/hash.ts';
import { lotMiddle, type Building, type BuildingKind } from '../world/buildings.ts';
import type { WorldChunk, WorldLayers } from '../world/chunks.ts';
import type { District, WorldDescription } from '../world/types.ts';
import { buildBlockGeometry, buildMassingGeometry } from './block-mesh.ts';
import { hullOf } from './building-hull.ts';
import {
  batchOf,
  chamferOf,
  CHAMFER_WIDTH,
  facadeFootprint,
  fitOf,
  FOUNDATION,
  leanOf,
  massingOf,
  plan,
  type BuildingBatch,
  type BuildingMassing,
  type Fit,
  type Lean,
} from './building-plan.ts';
import type { ChunkDetail } from './streaming.ts';

// The plan of a building is drawn in `building-plan.ts` and its outline in
// `building-hull.ts`; this is the door callers already import.
export { OUTLINE_WIDTH } from './building-hull.ts';
export { CORNICE, massingOf, standingGround, type BuildingBatch, type BuildingMassing } from './building-plan.ts';

/** A colour as the renderer wants it: three floats in the working colour space. */
export type Rgb = readonly [number, number, number];

/** One building, ready for a batch. */
export interface BuildingPlacement {
  building: Building;
  massing: BuildingMassing;
  batch: BuildingBatch;
  /** The shell, in the building's own frame. */
  shell: BufferGeometry;
  /** The inverted hull that outlines it, in the same frame. */
  hull: BufferGeometry;
  /** The building's frame in the world. */
  matrix: Matrix4;
}

/** The generator's bay and floor, in metres. Both are wider than a real tower's:
 * the camera looks down from 60 m, and every window it cannot see is geometry
 * the frame pays for. */
const BAY_WIDTH = 4.2;
const FLOOR_HEIGHT = 4;

/**
 * The colours each kind of block is built in. A tower takes the masonry palette
 * of the generator instead, which is what its material is written against.
 */
const BLOCK_PALETTE: Record<BuildingKind, readonly number[]> = {
  tower: [0xb4afa1],
  'mid-rise': [0xb0a99d, 0xa89c8a, 0xbcae97],
  // Bare concrete.
  'parking-garage': [0xa7a59f, 0x9d9c98],
  'shop-row': [0xc9b394, 0xd0a07c, 0xb9a88c, 0xcdc0a6],
  house: [0xd8c9a8, 0xc9b190, 0xbfc2ad, 0xd6b7a2, 0xc0ccc6, 0xe0d3b6],
  warehouse: [0x9aa0a2, 0x8e8f8a, 0xa39a8c],
  roadhouse: [0xd2c6ad, 0xc2a98c, 0xcfb9a0],
};

/** What a building's geometry asks about the world around it. */
export interface BuildingLookup {
  /** The carved height at a place: the ground a building stands on. */
  heightAt(x: number, y: number): number;
  /** The district a building's lot stands in, which says how tall it builds. */
  districtOf(building: Building): District;
  /** Which front corner of a lot faces a junction, as {@link BuildingMassing.chamfer}. */
  chamferOf(building: Building): number;
}

/** The lookup a world answers with, built once and shared by every chunk of it. */
export function buildingLookup(world: WorldDescription, layers: WorldLayers): BuildingLookup {
  return {
    heightAt: (x, y) => layers.carve.heightAt(x, y),
    districtOf: (building) => world.districts[building.district] as District,
    chamferOf: (building) => chamferOf(building, layers.graph),
  };
}

/**
 * Build the buildings of one chunk, in the order the chunk lists them. Each
 * placement owns its geometry until the caller has copied it into a batch.
 *
 * The detail is the building LOD of spec section 9.2, picked once from how far
 * the chunk stands. Near detail generates the facades. Mid detail builds every
 * building as a block, however tall it stands: a generated facade is the
 * dearest thing a chunk builds and its windows are a metre across. Far detail
 * is the massing alone, one box per building. Every detail is outlined,
 * because the outline is what the skyline reads by (spec section 10.1).
 */
export function buildChunkBuildings(
  chunk: WorldChunk,
  lookup: BuildingLookup,
  detail: ChunkDetail = 'near',
): BuildingPlacement[] {
  const out: BuildingPlacement[] = [];
  for (const building of chunk.buildings) {
    const massing = massingOf(building, lookup.districtOf(building), lookup.chamferOf(building));
    const generated = batchOf(building.kind, massing);
    const batch = detail === 'near' ? generated : 'block';
    // A tower keeps the colour of its facade at every detail, so the skyline
    // does not change colour where the detail steps down.
    const tint = tintOf(building, generated);
    const shell =
      batch === 'facade'
        ? facadeGeometry(building, massing, tint)
        : detail === 'far'
          ? buildMassingGeometry(massing, tint)
          : buildBlockGeometry(building.kind, massing, tint);
    const box = centreOnLot(shell);
    // A block fills its massing; a generated facade comes back narrower than
    // one, so where the lot has a wall against it the shell is stretched to
    // reach it.
    const wall = building.shared.left || building.shared.right;
    const fit = fitOf({ width: box.max.x - box.min.x, depth: box.max.z - box.min.z }, massing, wall);
    const hull = hullOf(massing, shell, box, fit);
    // A lot on a bend leans its side edges, and a wall it shares follows them.
    const lean = leanOf(building, massing);
    if (lean !== undefined) {
      leanGeometry(shell, lean, fit);
      leanGeometry(hull, lean, fit);
    }
    out.push({ building, massing, batch, shell, hull, matrix: matrixOf(building, lookup, massing, fit) });
  }
  return out;
}

/** Vertices a chunk's buildings cost: every shell and every hull. */
export function buildingVertices(placements: readonly BuildingPlacement[]): number {
  let count = 0;
  for (const placed of placements) {
    count += placed.shell.getAttribute('position').count + placed.hull.getAttribute('position').count;
  }
  return count;
}

/**
 * Draw calls a chunk spends on its buildings: one batch of generated facades,
 * one of blocks, and one of the hulls that outline both. A chunk with no
 * building of a kind pays nothing for it.
 */
export function buildingDrawCalls(chunk: WorldChunk): number {
  let facades = 0;
  let blocks = 0;
  for (const building of chunk.buildings) {
    if (batchOf(building.kind, plan(building)) === 'facade') facades++;
    else blocks++;
  }
  if (facades + blocks === 0) return 0;
  return (facades > 0 ? 1 : 0) + (blocks > 0 ? 1 : 0) + 1;
}

/** The colour a building is dressed in, from its own seed. */
function tintOf(building: Building, batch: BuildingBatch): Rgb {
  const hex =
    batch === 'facade'
      ? pickBuildingColor(building.seed)
      : (BLOCK_PALETTE[building.kind][hashInts(building.seed, 2) % BLOCK_PALETTE[building.kind].length] as number);
  const colour = new Color(hex);
  return [colour.r, colour.g, colour.b];
}

/**
 * A generated facade, tagged with the building's own colour so one material
 * dresses every tower in the batch.
 */
function facadeGeometry(building: Building, massing: BuildingMassing, tint: Rgb): BufferGeometry {
  const footprint = facadeFootprint(massing);
  const mesh = new SkyscraperGenerator({
    seed: building.seed,
    totalHeight: massing.height,
    floorHeight: FLOOR_HEIGHT,
    bayWidth: BAY_WIDTH,
    footprint,
    // The cut corner faces the junction, and there is only ever one to face.
    chamferWidth: massing.chamfer === 0 ? 0 : Math.min(CHAMFER_WIDTH, footprint.width * 0.25),
    chamferCornerX: massing.chamfer === 0 ? 0 : massing.chamfer,
    chamferCornerZ: 1,
  }).build();
  const geometry = mesh.geometry;
  const count = geometry.getAttribute('position').count;
  const tints = new Float32Array(count * 3);
  for (let v = 0; v < count; v++) {
    tints[v * 3] = tint[0];
    tints[v * 3 + 1] = tint[1];
    tints[v * 3 + 2] = tint[2];
  }
  geometry.setAttribute('tint', new BufferAttribute(tints, 3));
  return geometry;
}

/**
 * Stand a shell in the middle of its lot. A generated facade is not centred on
 * the footprint it was given — a chamfer takes one corner off and a cornice
 * overhangs the rest — so the box it really fills is what is centred, and the
 * whole of it then has the same room around it.
 */
function centreOnLot(shell: BufferGeometry): Box3 {
  shell.computeBoundingBox();
  const box = shell.boundingBox ?? new Box3();
  const dx = -(box.max.x + box.min.x) / 2;
  const dz = -(box.max.z + box.min.z) / 2;
  // The move is written straight into the positions, and the box is moved with
  // them: a shell of a hundred thousand vertices is not walked three times to
  // save a dozen lines.
  const position = shell.getAttribute('position') as BufferAttribute;
  const array = position.array as Float32Array;
  for (let i = 0; i < array.length; i += 3) {
    array[i] = (array[i] as number) + dx;
    array[i + 2] = (array[i + 2] as number) + dz;
  }
  position.needsUpdate = true;
  box.min.x += dx;
  box.max.x += dx;
  box.min.z += dz;
  box.max.z += dz;
  return box;
}

/**
 * Lean a geometry built square in its massing onto the side edges of its lot,
 * as {@link Lean} says, in place.
 *
 * The lean is in metres of the building's frame, and a shell is drawn through
 * a matrix that scales it by the fit, so each place is taken to metres, leaned
 * and taken back. A generated facade carries the room behind each window as a
 * place, and it is leaned with the wall. The normals are turned by the inverse
 * transpose of the lean, so a leaning wall is lit as the way it now faces.
 */
function leanGeometry(geometry: BufferGeometry, lean: Lean, fit: Fit): void {
  const place = (name: string): Float32Array | undefined =>
    (geometry.getAttribute(name) as BufferAttribute | undefined)?.array as Float32Array | undefined;
  const positions = place('position') as Float32Array;
  const normals = place('normal');
  // Normals first: they are turned by the lean at the place before it moves.
  if (normals !== undefined) {
    for (let i = 0; i < positions.length; i += 3) {
      const x = positions[i] as number;
      const depth = (positions[i + 2] as number) * fit.across;
      const scale = lean.scale + lean.scaleSlope * depth;
      // How far `x` moves for each unit of `z`, in the shell's own units.
      const shear = fit.across * (lean.scaleSlope * x + lean.shiftSlope / fit.along);
      const nx = (normals[i] as number) / scale;
      const ny = normals[i + 1] as number;
      const nz = (normals[i + 2] as number) - shear * nx;
      const span = Math.hypot(nx, ny, nz) || 1;
      normals[i] = nx / span;
      normals[i + 1] = ny / span;
      normals[i + 2] = nz / span;
    }
  }
  for (const array of [positions, place('roomCenter')]) {
    if (array === undefined) continue;
    for (let i = 0; i < array.length; i += 3) {
      const depth = (array[i + 2] as number) * fit.across;
      const scale = lean.scale + lean.scaleSlope * depth;
      array[i] = scale * (array[i] as number) + (lean.shift + lean.shiftSlope * depth) / fit.along;
    }
  }
  geometry.computeBoundingBox();
}

/**
 * Where a building stands, as the matrix from its own frame to the world.
 *
 * The frame is turned so `z` looks at the road the lot fronts, which is the way
 * `Building.facing` points. It stands on the lowest of the lot's four corners,
 * sunk by {@link FOUNDATION}: on a slope a wall is then buried at one end rather
 * than standing clear of the ground at the other. Where the lot takes its margin
 * on one side only, the frame moves along the frontage by
 * {@link BuildingMassing.offset}, and a wall it shares stretches it along the
 * frontage.
 */
function matrixOf(building: Building, lookup: BuildingLookup, massing: BuildingMassing, fit: Fit): Matrix4 {
  let ground = Infinity;
  for (const corner of building.lot) ground = Math.min(ground, lookup.heightAt(corner.x, corner.y));
  const middle = lotMiddle(building.lot);
  // A turn about the world's up axis takes the local frame's z to the heading
  // the lot faces; the quarter turn is the step from a heading on the map to an
  // angle about that axis.
  const turn = new Quaternion().setFromAxisAngle(new Vector3(0, 1, 0), Math.PI / 2 - building.facing);
  // The shell is built about its own middle, so the lot's margins move the frame
  // and not the geometry. The frame's own x axis is the way along the frontage.
  const along = new Vector3(1, 0, 0).applyQuaternion(turn).multiplyScalar(massing.offset);
  const at = new Vector3(middle.x + along.x, ground - FOUNDATION, middle.y + along.z);
  return new Matrix4().compose(at, turn, new Vector3(fit.along, fit.across, fit.across));
}
