/**
 * The buildings of one chunk, as geometry (spec sections 9.2, 10.1, 10.3).
 *
 * `buildings.ts` says where a building stands and what kind it is. This says
 * what it looks like: the shell that is generated for it and where that shell
 * is placed. `building-plan.ts` says how big it is and what ground it may
 * cover; `building-hull.ts` outlines it. This file is the door onto all three.
 *
 * A tower and a mid-rise block are generated by `SkyscraperGenerator`, which
 * gives the chamfers, setbacks, string courses and varied bays of spec section
 * 10.3 from one seed. Every other kind is a few boxes from `block-mesh.ts`; so
 * is a tower on a lot too narrow to generate a facade on, because the generator
 * needs room for its bays.
 *
 * A building never stands on a road, by construction (spec section 1.1). The lot
 * is already inside its parcel, and a parcel is the land the road footprint
 * leaves; the shell is then fitted inside the room the plan leaves it. Whatever
 * still reaches past that room is taken in by the scale of the placement, so
 * the last step is measured rather than estimated, and the sweep checks it.
 *
 * A building's own frame has the middle of its lot at the origin, `x` along the
 * frontage, `z` towards the road and `y` up from the ground it stands on. The
 * matrix of a placement is what puts that frame in the world. A shell is built
 * square in that frame; where its lot shares a side edge, its places are then
 * leaned along `x` to follow the lot's side edges, which a matrix cannot do on
 * a lot that is wider at its front than at its back.
 *
 * Nothing here touches the renderer or TSL, so it runs headless and the tests
 * read it directly.
 */
import { Box3, BufferAttribute, BufferGeometry, Color, Matrix4, Quaternion, Vector3 } from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {
  SkyscraperGenerator,
  pickBuildingColor,
  type SkyscraperGeneratorParameters,
} from 'three/examples/jsm/generators/city/SkyscraperGenerator.js';
import { hashInts } from '../core/hash.ts';
import { lotMiddle, type Building, type BuildingKind } from '../world/buildings.ts';
import type { WorldChunk, WorldLayers } from '../world/chunks.ts';
import type { District, WorldDescription } from '../world/types.ts';
import { buildBlockGeometry, buildDressGeometry, buildMassingGeometry, roofDeckOf, type BlockStyle } from './block-mesh.ts';
import { hullOf } from './building-hull.ts';
import { boxesOf, shapeOf, type BuildingShape, type ShapeBox } from './building-shape.ts';
import {
  batchOf,
  chamferOf,
  CHAMFER_WIDTH,
  facadeFootprint,
  fitOf,
  FOUNDATION,
  leanOf,
  massingOf,
  plan,
  type BuildingBatch,
  type BuildingMassing,
  type Fit,
  type Lean,
} from './building-plan.ts';
import type { RoofDeck } from './roof-dress.ts';
import type { ChunkDetail } from './streaming.ts';

// The plan of a building is drawn in `building-plan.ts` and its outline in
// `building-hull.ts`; this is the door callers already import.
export { OUTLINE_WIDTH } from './building-hull.ts';
export { CORNICE, massingOf, standingGround, type BuildingBatch, type BuildingMassing } from './building-plan.ts';
export { shapeOf, type BuildingShape } from './building-shape.ts';

/** A colour as the renderer wants it: three floats in the working colour space. */
export type Rgb = readonly [number, number, number];

/** One building, ready for a batch. */
export interface BuildingPlacement {
  building: Building;
  massing: BuildingMassing;
  batch: BuildingBatch;
  /** The shell, in the building's own frame. */
  shell: BufferGeometry;
  /**
   * What stands on the roof, in the same frame, or undefined where the roof
   * carries nothing. It joins the block batch and is deliberately not part of
   * the shell: the outline hull is drawn around the shell, and the camera reads
   * the hull, so a mast here is never something the camera climbs.
   */
  dress: BufferGeometry | undefined;
  /** The inverted hull that outlines it, in the same frame. */
  hull: BufferGeometry;
  /** The building's frame in the world. */
  matrix: Matrix4;
}

/**
 * Metres a tier of a setback tower is sunk into the one below it. The tier
 * above stands on the ledge the tier below caps itself with, and the ledge is
 * measured off the built geometry rather than predicted; the overlap is what
 * keeps a millimetre of daylight out of the joint if the measurement lands low.
 */
const TIER_OVERLAP = 0.5;

/**
 * The base and the crown a tier over the ground is built with. The generator
 * gives every building it builds a ground floor, and a ground floor is shops:
 * awnings and display glazing sixty metres up read as a mistake. A base this
 * tall is two floors or more, which is what makes the generator build its grand
 * arcade there instead, and an arcade at a setback ledge reads as the loggia a
 * tower of spec section 10.3 carries.
 */
const LEDGE_TIER = { base: 0.35, crown: 0.12 };

/**
 * Metres two boxes of a shape may differ in height and still be one box at far
 * detail. A chunk that far out is half a kilometre away, where a storey or two
 * is less than a pixel; running the boxes together is what holds the far tier
 * inside its vertex cap.
 */
const FAR_STEP = 9;

/** Metres each way a terrace must measure before anything is laid out on it. */
const MIN_TERRACE = 4;

/**
 * The generator's `baseStyle`, which its types do not carry: it is drawn from
 * the seed by default, and a tier over the ground asks for the arcade by name.
 */
type TierParameters = Partial<SkyscraperGeneratorParameters> & { baseStyle?: 'arcade' | 'storefront' };

/**
 * The colours each kind of block is built in. A tower takes the masonry palette
 * of the generator instead, which is what its material is written against.
 */
const BLOCK_PALETTE: Record<BuildingKind, readonly number[]> = {
  tower: [0xb4afa1],
  'mid-rise': [0xb0a99d, 0xa89c8a, 0xbcae97],
  // Bare concrete.
  'parking-garage': [0xa7a59f, 0x9d9c98],
  'shop-row': [0xc9b394, 0xd0a07c, 0xb9a88c, 0xcdc0a6],
  house: [0xd8c9a8, 0xc9b190, 0xbfc2ad, 0xd6b7a2, 0xc0ccc6, 0xe0d3b6],
  warehouse: [0x9aa0a2, 0x8e8f8a, 0xa39a8c],
  roadhouse: [0xd2c6ad, 0xc2a98c, 0xcfb9a0],
};

/** What a building's geometry asks about the world around it. */
export interface BuildingLookup {
  /** The carved height at a place: the ground a building stands on. */
  heightAt(x: number, y: number): number;
  /** The district a building's lot stands in, which says how tall it builds. */
  districtOf(building: Building): District;
  /** Which front corner of a lot faces a junction, as {@link BuildingMassing.chamfer}. */
  chamferOf(building: Building): number;
}

/** The lookup a world answers with, built once and shared by every chunk of it. */
export function buildingLookup(world: WorldDescription, layers: WorldLayers): BuildingLookup {
  return {
    heightAt: (x, y) => layers.carve.heightAt(x, y),
    districtOf: (building) => world.districts[building.district] as District,
    chamferOf: (building) => chamferOf(building, layers.graph),
  };
}

/**
 * Build the buildings of one chunk, in the order the chunk lists them. Each
 * placement owns its geometry until the caller has copied it into a batch.
 *
 * The detail is the building LOD of spec section 9.2, picked once from how far
 * the chunk stands. Near detail generates the facades. Mid detail builds every
 * building as a block, however tall it stands: a generated facade is the
 * dearest thing a chunk builds and its windows are a metre across. Far detail
 * is the massing alone, one box per building. Every detail is outlined,
 * because the outline is what the skyline reads by (spec section 10.1).
 */
export function buildChunkBuildings(
  chunk: WorldChunk,
  lookup: BuildingLookup,
  detail: ChunkDetail = 'near',
): BuildingPlacement[] {
  const out: BuildingPlacement[] = [];
  for (const building of chunk.buildings) {
    const district = lookup.districtOf(building);
    const massing = massingOf(building, district, lookup.chamferOf(building));
    const generated = batchOf(building.kind, massing);
    const batch = detail === 'near' ? generated : 'block';
    // A tower keeps the colour of its facade at every detail, so the skyline
    // does not change colour where the detail steps down.
    const tint = tintOf(building, generated);
    // Every variant and every piece of rooftop plant is drawn from the
    // building's own seed and the wealth of the district it stands in, so the
    // same building is dressed the same way in every session.
    const style: BlockStyle = { seed: building.seed, wealth: district.wealth, detail: detail === 'near' ? 'near' : 'mid' };
    // How the building is massed inside its box: the same shape at every
    // detail, laid out on whatever rectangle that detail builds on.
    const shape = shapeOf(building.seed, building.kind, massing, building.shared);
    let shell: BufferGeometry;
    let dress: BufferGeometry | undefined;
    if (batch === 'facade') {
      const built = facadeGeometry(building, massing, shape, tint);
      shell = built.shell;
      // A generated tower's roofs are measured off the geometry the generator
      // built, because its crown draws in from the footprint it was given.
      dress = dressOf(built.decks, style, tint);
    } else if (detail === 'far') {
      shell = buildMassingGeometry(massing, tint, farBoxes(shape, massing));
    } else {
      const built = buildBlockGeometry(building.kind, massing, tint, style, boxesOf(shape, massing, massing.height, 0));
      shell = built.shell;
      dress = built.dress;
    }
    const box = centreOnLot(shell, dress);
    // A block fills its massing; a generated facade comes back narrower than
    // one, so where the lot has a wall against it the shell is stretched to
    // reach it.
    const wall = building.shared.left || building.shared.right;
    const fit = fitOf({ width: box.max.x - box.min.x, depth: box.max.z - box.min.z }, massing, wall);
    const hull = hullOf(massing, shell, box, fit, shape);
    // A lot on a bend leans its side edges, and a wall it shares follows them.
    const lean = leanOf(building, massing);
    if (lean !== undefined) {
      leanGeometry(shell, lean, fit);
      leanGeometry(hull, lean, fit);
      if (dress !== undefined) leanGeometry(dress, lean, fit);
    }
    out.push({ building, massing, batch, shell, dress, hull, matrix: matrixOf(building, lookup, massing, fit) });
  }
  return out;
}

/**
 * Everything the roof dresser lays on one building, as one geometry. A shape
 * of several boxes has a roof on each of them — the terrace of a podium, the
 * arm of an L — and each is dressed on its own.
 */
function dressOf(decks: readonly RoofDeck[], style: BlockStyle, tint: Rgb): BufferGeometry | undefined {
  const built: BufferGeometry[] = [];
  for (let i = 0; i < decks.length; i++) {
    // Each roof is dressed from its own draw, so a podium terrace and the tower
    // over it do not carry the same water tank in the same corner.
    const dressed = buildDressGeometry(decks[i], { ...style, seed: style.seed + i * 977 }, tint);
    if (dressed !== undefined) built.push(dressed);
  }
  if (built.length === 0) return undefined;
  return built.length === 1 ? (built[0] as BufferGeometry) : (mergeGeometries(built) as BufferGeometry);
}

/**
 * The boxes of a shape at far detail: the boxes that stand to the same height
 * run together into the one box around them.
 *
 * Far detail is a skyline read from half a kilometre, and a skyline is heights
 * and footprints. The wings of a courtyard block are one box there, which keeps
 * the far tier inside its vertex cap; a podium and the tower over it are two,
 * because the step between them is what the silhouette is.
 */
function farBoxes(shape: BuildingShape, massing: BuildingMassing): ShapeBox[] {
  const out: ShapeBox[] = [];
  for (const box of boxesOf(shape, massing, massing.height, 0)) {
    const same = out.find((other) => Math.abs(other.from - box.from) < 0.01 && Math.abs(other.to - box.to) < FAR_STEP);
    if (same === undefined) {
      out.push({ ...box });
      continue;
    }
    const x0 = Math.min(same.x - same.width / 2, box.x - box.width / 2);
    const x1 = Math.max(same.x + same.width / 2, box.x + box.width / 2);
    const z0 = Math.min(same.z - same.depth / 2, box.z - box.depth / 2);
    const z1 = Math.max(same.z + same.depth / 2, box.z + box.depth / 2);
    same.x = (x0 + x1) / 2;
    same.z = (z0 + z1) / 2;
    same.width = x1 - x0;
    same.depth = z1 - z0;
  }
  return out;
}

/** Vertices a chunk's buildings cost: every shell, every roof and every hull. */
export function buildingVertices(placements: readonly BuildingPlacement[]): number {
  let count = 0;
  for (const placed of placements) {
    count += placed.shell.getAttribute('position').count + placed.hull.getAttribute('position').count;
    count += placed.dress?.getAttribute('position').count ?? 0;
  }
  return count;
}

/**
 * Draw calls a chunk spends on its buildings: one batch of generated facades,
 * one of blocks, and one of the hulls that outline both. A chunk with no
 * building of a kind pays nothing for it.
 */
export function buildingDrawCalls(chunk: WorldChunk): number {
  let facades = 0;
  let blocks = 0;
  for (const building of chunk.buildings) {
    if (batchOf(building.kind, plan(building)) === 'facade') facades++;
    else blocks++;
  }
  if (facades + blocks === 0) return 0;
  // A generated tower's roof dressing joins the block batch, so a chunk of
  // towers alone still draws one.
  return (facades > 0 ? 1 : 0) + 1 + 1;
}

/** The colour a building is dressed in, from its own seed. */
function tintOf(building: Building, batch: BuildingBatch): Rgb {
  const hex =
    batch === 'facade'
      ? pickBuildingColor(building.seed)
      : (BLOCK_PALETTE[building.kind][hashInts(building.seed, 2) % BLOCK_PALETTE[building.kind].length] as number);
  const colour = new Color(hex);
  return [colour.r, colour.g, colour.b];
}

/**
 * A generated facade: one `SkyscraperGenerator` call per box of the building's
 * shape, merged, and tagged with the building's own colour so one material
 * dresses every tower in the batch.
 *
 * A box that stands on the ground is built from the ground, even where another
 * box covers its first few storeys: the tower of a podium shares one wall with
 * its podium down to the pavement, and the shopfront it is given is then buried
 * inside the podium rather than standing over the street. A box that stands on
 * the ledge of the box below it is built from that ledge, measured off the
 * geometry rather than predicted, because the generator rounds a height to
 * whole floors and a whole floor is four metres.
 *
 * The decks that come back are the roofs the dresser fills: each box's own
 * crown slab, cut down to the part of it no other box stands on.
 */
function facadeGeometry(
  building: Building,
  massing: BuildingMassing,
  shape: BuildingShape,
  tint: Rgb,
): { shell: BufferGeometry; decks: RoofDeck[] } {
  const footprint = facadeFootprint(massing);
  const boxes = boxesOf(shape, footprint, massing.height, massing.chamfer);
  const built: BufferGeometry[] = [];
  const decks: RoofDeck[] = [];
  // Only the box that reaches the top draws in at its crown: a setback inside
  // the run of a building is a ledge with nothing standing on it.
  let crown = 0;
  for (const box of boxes) crown = Math.max(crown, box.to);
  let ledge = 0;
  for (let i = 0; i < boxes.length; i++) {
    const box = boxes[i] as ShapeBox;
    const stands = box.from === 0 ? 0 : Math.max(0, ledge - TIER_OVERLAP);
    const geometry = tierGeometry(building.seed, box, stands, crown, shape);
    translate(geometry, box.x, stands, box.z);
    const deck = roofDeckOf(geometry);
    ledge = deck?.top ?? stands + (box.to - stands);
    if (box.terrace !== undefined && deck !== undefined) {
      const clipped = clip(deck, box.terrace);
      if (clipped !== undefined) decks.push(clipped);
    }
    built.push(geometry);
  }
  const geometry = built.length === 1 ? (built[0] as BufferGeometry) : (mergeGeometries(built) as BufferGeometry);
  const count = geometry.getAttribute('position').count;
  const tints = new Float32Array(count * 3);
  for (let v = 0; v < count; v++) {
    tints[v * 3] = tint[0];
    tints[v * 3 + 1] = tint[1];
    tints[v * 3 + 2] = tint[2];
  }
  geometry.setAttribute('tint', new BufferAttribute(tints, 3));
  return { shell: geometry, decks };
}

/** One box of a shape, built about its own middle and standing on the ground. */
function tierGeometry(seed: number, box: ShapeBox, stands: number, crown: number, shape: BuildingShape): BufferGeometry {
  const height = Math.max(shape.floorHeight * 3, box.to - stands);
  const parameters: TierParameters = {
    seed,
    totalHeight: height,
    floorHeight: shape.floorHeight,
    bayWidth: shape.bayWidth,
    footprint: { width: box.width, depth: box.depth },
    // The cut corner faces the junction, and there is only ever one to face.
    chamferWidth: box.chamfer === 0 ? 0 : Math.min(CHAMFER_WIDTH, box.width * 0.25),
    chamferCornerX: box.chamfer === 0 ? 0 : box.chamfer,
    chamferCornerZ: 1,
  };
  if (box.to < crown) parameters.setbackDepth = 0;
  if (stands > 0) {
    parameters.tierFractions = LEDGE_TIER;
    parameters.baseStyle = 'arcade';
  }
  return new SkyscraperGenerator(parameters).build().geometry;
}

/** Move a built geometry, and the rooms its glass looks into, in place. */
function translate(geometry: BufferGeometry, dx: number, dy: number, dz: number): void {
  for (const name of ['position', 'roomCenter']) {
    const attribute = geometry.getAttribute(name) as BufferAttribute | undefined;
    if (attribute === undefined) continue;
    const array = attribute.array as Float32Array;
    for (let i = 0; i < array.length; i += 3) {
      array[i] = (array[i] as number) + dx;
      array[i + 1] = (array[i + 1] as number) + dy;
      array[i + 2] = (array[i + 2] as number) + dz;
    }
    attribute.needsUpdate = true;
  }
}

/**
 * A measured deck cut down to the rectangle of it no other box of the shape
 * stands on, or undefined where nothing of it is left. The dresser lays out
 * rectangles, so a roof a tower stands in the middle of offers the strip in
 * front of the tower rather than the whole slab.
 */
function clip(deck: RoofDeck, room: { x: number; z: number; width: number; depth: number }): RoofDeck | undefined {
  const x0 = Math.max(deck.x - deck.hw, room.x - room.width / 2);
  const x1 = Math.min(deck.x + deck.hw, room.x + room.width / 2);
  const z0 = Math.max(deck.z - deck.hd, room.z - room.depth / 2);
  const z1 = Math.min(deck.z + deck.hd, room.z + room.depth / 2);
  if (x1 - x0 < MIN_TERRACE || z1 - z0 < MIN_TERRACE) return undefined;
  return { x: (x0 + x1) / 2, z: (z0 + z1) / 2, hw: (x1 - x0) / 2, hd: (z1 - z0) / 2, top: deck.top };
}

/**
 * Stand a shell, and whatever is dressed onto it, in the middle of its lot. A generated facade is not centred on
 * the footprint it was given — a chamfer takes one corner off and a cornice
 * overhangs the rest — so the box it really fills is what is centred, and the
 * whole of it then has the same room around it.
 */
function centreOnLot(shell: BufferGeometry, dress: BufferGeometry | undefined): Box3 {
  shell.computeBoundingBox();
  const box = shell.boundingBox ?? new Box3();
  const dx = -(box.max.x + box.min.x) / 2;
  const dz = -(box.max.z + box.min.z) / 2;
  // The move is written straight into the positions, and the box is moved with
  // them: a shell of a hundred thousand vertices is not walked three times to
  // save a dozen lines. The dressing stands on the shell, so it moves with it
  // and is not measured itself.
  for (const geometry of dress === undefined ? [shell] : [shell, dress]) {
    const position = geometry.getAttribute('position') as BufferAttribute;
    const array = position.array as Float32Array;
    for (let i = 0; i < array.length; i += 3) {
      array[i] = (array[i] as number) + dx;
      array[i + 2] = (array[i + 2] as number) + dz;
    }
    position.needsUpdate = true;
  }
  box.min.x += dx;
  box.max.x += dx;
  box.min.z += dz;
  box.max.z += dz;
  return box;
}

/**
 * Lean a geometry built square in its massing onto the side edges of its lot,
 * as {@link Lean} says, in place.
 *
 * The lean is in metres of the building's frame, and a shell is drawn through
 * a matrix that scales it by the fit, so each place is taken to metres, leaned
 * and taken back. A generated facade carries the room behind each window as a
 * place, and it is leaned with the wall. The normals are turned by the inverse
 * transpose of the lean, so a leaning wall is lit as the way it now faces.
 */
function leanGeometry(geometry: BufferGeometry, lean: Lean, fit: Fit): void {
  const place = (name: string): Float32Array | undefined =>
    (geometry.getAttribute(name) as BufferAttribute | undefined)?.array as Float32Array | undefined;
  const positions = place('position') as Float32Array;
  const normals = place('normal');
  // Normals first: they are turned by the lean at the place before it moves.
  if (normals !== undefined) {
    for (let i = 0; i < positions.length; i += 3) {
      const x = positions[i] as number;
      const depth = (positions[i + 2] as number) * fit.across;
      const scale = lean.scale + lean.scaleSlope * depth;
      // How far `x` moves for each unit of `z`, in the shell's own units.
      const shear = fit.across * (lean.scaleSlope * x + lean.shiftSlope / fit.along);
      const nx = (normals[i] as number) / scale;
      const ny = normals[i + 1] as number;
      const nz = (normals[i + 2] as number) - shear * nx;
      const span = Math.hypot(nx, ny, nz) || 1;
      normals[i] = nx / span;
      normals[i + 1] = ny / span;
      normals[i + 2] = nz / span;
    }
  }
  for (const array of [positions, place('roomCenter')]) {
    if (array === undefined) continue;
    for (let i = 0; i < array.length; i += 3) {
      const depth = (array[i + 2] as number) * fit.across;
      const scale = lean.scale + lean.scaleSlope * depth;
      array[i] = scale * (array[i] as number) + (lean.shift + lean.shiftSlope * depth) / fit.along;
    }
  }
  geometry.computeBoundingBox();
}

/**
 * Where a building stands, as the matrix from its own frame to the world.
 *
 * The frame is turned so `z` looks at the road the lot fronts, which is the way
 * `Building.facing` points. It stands on the lowest of the lot's four corners,
 * sunk by {@link FOUNDATION}: on a slope a wall is then buried at one end rather
 * than standing clear of the ground at the other. Where the lot takes its margin
 * on one side only, the frame moves along the frontage by
 * {@link BuildingMassing.offset}, and a wall it shares stretches it along the
 * frontage.
 */
function matrixOf(building: Building, lookup: BuildingLookup, massing: BuildingMassing, fit: Fit): Matrix4 {
  let ground = Infinity;
  for (const corner of building.lot) ground = Math.min(ground, lookup.heightAt(corner.x, corner.y));
  const middle = lotMiddle(building.lot);
  // A turn about the world's up axis takes the local frame's z to the heading
  // the lot faces; the quarter turn is the step from a heading on the map to an
  // angle about that axis.
  const turn = new Quaternion().setFromAxisAngle(new Vector3(0, 1, 0), Math.PI / 2 - building.facing);
  // The shell is built about its own middle, so the lot's margins move the frame
  // and not the geometry. The frame's own x axis is the way along the frontage.
  const along = new Vector3(1, 0, 0).applyQuaternion(turn).multiplyScalar(massing.offset);
  const at = new Vector3(middle.x + along.x, ground - FOUNDATION, middle.y + along.z);
  return new Matrix4().compose(at, turn, new Vector3(fit.along, fit.across, fit.across));
}
