/**
 * Which style a tall building is dressed in (spec section 10.3).
 *
 * `building-plan.ts` says how big a tower is and `building-shape.ts` what
 * stands inside its box. This says what that box looks like: classical masonry,
 * a glass curtain wall, raw Brutalist concrete, an Art Deco stack of setbacks,
 * or Miami pastel. The choice comes from the zone, the district's wealth and
 * density, the skyline over the lot and the building's own seed, so the same
 * tower is dressed the same way in every session.
 *
 * Colour follows the style and not the district: each style carries its own
 * palette, and the seed picks from it. Masonry draws its stone from a palette of
 * `building-mesh.ts`.
 *
 * Only masonry is generated by `SkyscraperGenerator`. The other four are built
 * from the box kit of `block-shell.ts` by `tall-mesh.ts`, so they join the
 * block batch a cell already draws and cost no draw call of their own. That is
 * the cheap half of the choice the issue offers: a curtain wall is a wall and a
 * shader, where a masonry facade is a bay and a window at a time.
 *
 * Pure, and free of three.js.
 */
import { hashInts } from '../../core/hash.ts';
import type { Building } from '../../world/city/buildings.ts';
import type { District } from '../../world/types.ts';
import type { BuildingPlan } from './building-shape.ts';

/** How a tall building is dressed. */
export type BuildingStyle = 'masonry' | 'glass' | 'brutalist' | 'deco' | 'miami';

/** The four styles that are built from boxes rather than generated. */
export type StyledLook = Exclude<BuildingStyle, 'masonry'>;

/**
 * Metres over the sea a lot may stand on and still count as coastal. The
 * renderer already measures the ground under every building for its matrix, so
 * this is the coast the Miami style reads without asking the world anything
 * new.
 */
const COAST_HEIGHT = 9;

/**
 * Metres a building must stand before it is dressed as Art Deco. The style is a
 * stack of setbacks with a stepped crown, and a stack needs the height
 * `building-shape.ts` asks of its `setbacks` plan.
 */
const DECO_HEIGHT = 55;

/**
 * The colours each style is built in, in the bright key of `docs/art-style.md`.
 * Glass is the tint of the curtain wall itself — cobalt, teal, bronze or plum;
 * Brutalist is raw concrete gone a warm lavender grey; Deco is warm stone;
 * Miami is pastel stucco.
 */
const STYLE_PALETTE: Record<StyledLook, readonly number[]> = {
  glass: [0x4a78c4, 0x2e8c8a, 0x9c7040, 0x5a4a82, 0x5f94d0, 0x3fa39a],
  brutalist: [0xb4abb8, 0xa89fb4, 0xc0b6bf, 0xaba2ae],
  deco: [0xe8cf9f, 0xdcb98a, 0xf0dcb0, 0xe0c090],
  miami: [0xf4a8bb, 0x8fe0d6, 0xf8cf78, 0xbfa6ec, 0xf2c4a2, 0xa8e09a],
};

/** The colour a styled building is dressed in, from its own seed. */
export function styleColour(look: StyledLook, seed: number): number {
  const palette = STYLE_PALETTE[look];
  return palette[hashInts(seed, 61) % palette.length] as number;
}

/**
 * The style a building is dressed in. Only a tower and a mid-rise have one;
 * every other kind is a house, a shop row or a shed, and none of them is a
 * style of spec section 10.3.
 *
 * Each style carries a weight, and the seed draws from the weights. Masonry
 * weighs the same everywhere, so it can stand anywhere; the other four are
 * common where the spec says they are and rare elsewhere, rather than banned:
 * one glass tower in a poor district is a landlord, not a mistake.
 *
 * `ground` is the metres the lot stands over the sea, which is what says
 * whether it is on the coast.
 */
export function styleOf(building: Building, district: District, ground: number, height: number): BuildingStyle {
  if (building.kind !== 'tower' && building.kind !== 'mid-rise') return 'masonry';
  const core = building.zone === 'core';
  const inner = building.zone === 'inner';
  const coast = ground <= COAST_HEIGHT;
  const weights: readonly (readonly [BuildingStyle, number])[] = [
    ['masonry', 4],
    ['glass', 0.3 + 1.7 * district.wealth + (core ? 0.7 : 0)],
    ['brutalist', 0.2 + 1.6 * (1 - district.wealth) * district.density + (inner ? 0.3 : 0)],
    // A stepped crown and a spire need a building tall enough to step.
    ['deco', height >= DECO_HEIGHT ? 0.2 + 1.9 * building.skyline : 0],
    ['miami', coast && (core || inner) ? 1.7 : 0.1],
  ];
  let total = 0;
  for (const [, weight] of weights) total += weight;
  let draw = (hashInts(building.seed, 60) / 0x100000000) * total;
  for (const [style, weight] of weights) {
    draw -= weight;
    if (draw <= 0) return style;
  }
  return 'masonry';
}

/**
 * The plan a style insists on, or undefined where it takes whatever its seed
 * draws. Art Deco is a stack of setbacks by definition, so it asks for one; the
 * shape falls back to a box where the lot has no room for a stack.
 */
export function planFor(style: BuildingStyle): BuildingPlan | undefined {
  return style === 'deco' ? 'setbacks' : undefined;
}
